### ISSUE TITLE
Add error response handling

### ISSUE THREAD

**Issue by nirvdrum** [simplygenius/atmos#6]
I've been trying to run a command with Atmos that fails without much indication why. If I just run it normally, I get:

```
undefined method `task_arn' for nil:NilClass
```

If I run it with the `--debug` flag, I can get the stack trace:

```
[exception=NoMethodError ] Unhandled exception: undefined method `task_arn' for nil:NilClass /home/nirvdrum/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/simplygenius-atmos-0.12.1/lib/simplygenius/atmos/providers/aws/container_manager.rb:220:in `run_task'
/home/nirvdrum/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/simplygenius-atmos-0.12.1/lib/simplygenius/atmos/commands/container.rb:190:in `block (2 levels) in execute'
/home/nirvdrum/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/climate_control-0.2.0/lib/climate_control/modifier.rb:31:in `run_block'
/home/nirvdrum/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/climate_control-0.2.0/lib/climate_control/modifier.rb:13:in `block in process'
/home/nirvdrum/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/climate_control-0.2.0/lib/climate_control/environment.rb:23:in `block in synchronize'
/home/nirvdrum/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/climate_control-0.2.0/lib/climate_control/environment.rb:20:in `synchronize'
/home/nirvdrum/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/climate_control-0.2.0/lib/climate_control/environment.rb:20:in `synchronize'
/home/nirvdrum/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/climate_control-0.2.0/lib/climate_control/modifier.rb:10:in `process'
/home/nirvdrum/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/climate_control-0.2.0/lib/climate_control.rb:10:in `modify'
/home/nirvdrum/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/simplygenius-atmos-0.12.1/lib/simplygenius/atmos/commands/container.rb:181:in `block in execute'
/home/nirvdrum/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/simplygenius-atmos-0.12.1/lib/simplygenius/atmos/providers/aws/auth_manager.rb:174:in `authenticate'
/home/nirvdrum/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/simplygenius-atmos-0.12.1/lib/simplygenius/atmos/commands/container.rb:180:in `execute'
/home/nirvdrum/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/clamp-1.3.2/lib/clamp/command.rb:66:in `run'
/home/nirvdrum/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/clamp-1.3.2/lib/clamp/subcommand/execution.rb:18:in `execute'
/home/nirvdrum/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/clamp-1.3.2/lib/clamp/command.rb:66:in `run'
/home/nirvdrum/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/clamp-1.3.2/lib/clamp/subcommand/execution.rb:18:in `execute'
/home/nirvdrum/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/clamp-1.3.2/lib/clamp/command.rb:66:in `run'
/home/nirvdrum/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/clamp-1.3.2/lib/clamp/command.rb:140:in `run'
/home/nirvdrum/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/simplygenius-atmos-0.12.1/lib/simplygenius/atmos/cli.rb:197:in `run'
/home/nirvdrum/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/simplygenius-atmos-0.12.1/exe/atmos:4:in `<top (required)>'
/home/nirvdrum/.rbenv/versions/2.6.6/bin/atmos:23:in `load'
/home/nirvdrum/.rbenv/versions/2.6.6/bin/atmos:23:in `<main>'
undefined method `task_arn' for nil:NilClass
```

The exception message really doesn't indicate what the failure is, however. It just tells me the code got into a state it doesn't know how to handle. The code in question looks like:

```ruby
resp = ecs.run_task(**task_opts)
task_arn = result[:task_arn] = resp.tasks.first.task_arn
task_id = result[:task_id] = task_arn.split('/').last
```

I modified that locally to print out the `resp` object and got:

```
#<#<Class:0x00005560182f7420>:Aws::ECS::Types::RunTaskResponse:0x556018e52ae0
    failures = [
        [0] #<#<Class:0x0000556018e4f3b8>:Aws::ECS::Types::Failure:0x556018e52950
            arn = nil,
            detail = nil,
            reason = "Capacity is unavailable at this time. Please try again later or in a different availability zone"
        >
    ],
    tasks = []
>
```

The `resp.failures[0].reason` message would have given me a really good idea about why things were failing. When I saw that, I realized AWS was having service issues.

I suggest adding in response verification would be much more user friendly. I don't know the underlying libraries well enough to tell if that's doable with some sort of global error handler or if each response object would need to have its `failures` value checked. I'd be happy with some sort of thrown exception that indicates what the upstream service error is.

**Comment by wr0ngway** [comment]
For now, I'm enabling  the global aws sdk logger to send to the atmos log at a debug level (visible when debug logging is enabled).  We can add more targeted response verification if this proves insufficient.

Added in 55dd3036b97a89eaaad361c06b55310e07a081da
